### ISSUE TITLE
Missuse of updateCoeffs. 

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_openfoam#3]
updateCoeffs is supposed to update the value of the field on boundaries based on internal values.
Please put it into a function called, e.g., overwriteBoundaryValues. This function can be called from updateCoeffs, but at least this would clarify that it is prescribing an external value from the model.

**Comment by AndreWeiner** [comment]
I was not aware of this convention. I did not really put too much thought into the design of the boundary condition because I simply copied an available _derived type_ boundary condition and modified some names and a few lines of functional code. If you would like to improve the code design, I'll be very thankful for a pull request.
